"""rename question_text to question

Revision ID: dbc7fd6adb87
Revises: 7bf00a48f0eb
Create Date: 2026-05-07 09:44:31.264272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbc7fd6adb87'
down_revision: Union[str, Sequence[str], None] = '7bf00a48f0eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('question', sa.Text(), nullable=False))
    op.drop_column('messages', 'question_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('messages', 'question')
    # ### end Alembic commands ###
